name = "discord-cmd-dev"

main = "src/index.ts"
compatibility_date = "2023-03-24"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "discord-cmd"
minify = true
define = {"import.meta.vitest"="false"}

